trigger:
  branches:
    include:
      - F104

pool:
  name: UniCircle

jobs:
- job: Test
  displayName: Run Tests for Club and Appointments
  pool:
    name: UniCircle
  steps:
    - checkout: self

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/backend'
        script: 'gradlew.bat test --tests com.unicircle.backend.ClubTest'
      displayName: 'Club Unit Test'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/backend'
        script: 'gradlew.bat test --tests com.unicircle.backend.AppointmentTest'
      displayName: 'Appointment Unit Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/build/test-results/test/*.xml'
        testRunTitle: 'JUnit Test Results'
        failTaskOnFailedTests: true