trigger:
  branches:
    include:
      - F108

pool:
  name: UniCircle

jobs:
- job: Test
  displayName: Run Tests for Friendship
  pool:
    name: UniCircle
  steps:
    - checkout: self

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/backend'
        script: 'gradlew.bat test --tests com.unicircle.backend.FriendshipTest'
      displayName: 'FriendshipService Unit Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/build/test-results/test/*.xml'
        testRunTitle: 'JUnit Test Results'
        failTaskOnFailedTests: true
