# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main


pool:
  name: UniCircle

variables:
  frontend: Frontend
  backend: Backend

steps:
 - task: NodeTool@0
   inputs:
     versionSource: 'spec'
     versionSpec: '22.x'
   displayName: 'Use Node.js 22'
    
 - task: Cache@2
   inputs:
     key: 'npm | "$(Agent.OS)" | package-lock.json'
     path: $(frontend)/node_modules

 - script: |
    cd $(frontend)
    npm install
    npm run build
   displayName: 'Build Unicircle React Frontend'

 - script: |
    set JAVA_HOME=D:\Coding\jdk 21
    set PATH=%JAVA_HOME%\bin;%PATH%
    java -version
   displayName: "Set JAVA_HOME for Backend"

 - task: Cache@2
   inputs:
     key: 'gradle | "$(Agent.OS)" | **/*.gradle*'
     path: $(USERPROFILE)/.gradle/caches

 - script: |
    cd $(backend)
    gradlew.bat clean build
   displayName: 'Build Spring Boot for UniCircle Backend'




