trigger:
  branches:
    include:
      - F104

pool:
  name: UniCircle

jobs:
  - job: Test
    displayName: Run ClubTest
    pool:
      name: UniCircle
    steps:
      - script: |
          cd $(Build.SourcesDirectory)
          gradlew.bat test --tests com.unicircle.Service.ClubTest
        displayName: Run ClubTest