trigger:
  branches:
    include:
      - F104

pool:
  name: UniCircle

jobs:
- job: Test
  displayName: Run Tests for Club and Appointments
  pool:
    name: UniCircle
  steps:
    - checkout: self

    - script: dir $(Build.SourcesDirectory)
      displayName: "List files in project root"

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/backend'
        script: 'gradlew.bat clean test --tests com.unicircle.backend.ClubTest'
      displayName: 'Run ClubTest'

    - task: CmdLine@2
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/backend'
        script: 'gradlew.bat clean test --tests com.unicircle.backend.AppointmentTest'
      displayName: 'Run AppointmentTest'


