# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main


pool:
  name: UniCircle

variables:
  frontend: Frontend
  backend: Backend

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Use Node.js 22'
    
  - script: |
      cd $(frontend)
      npm install
      npm run build
    displayName: 'Build Unicircle React Frontend'

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Use JDK 21 for UniCircle Backend'

  - script: |
      cd $(backend)
      ./mvnw clean package
    displayName: 'Build Spring Boot for UniCircle Backend'


