# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main


pool:
  name: UniCircle

variables:
  frontend: Frontend
  backend: Backend

steps:
 - task: NodeTool@0
   inputs:
     versionSource: 'spec'
     versionSpec: '22.x'
   displayName: 'Use Node.js 22'

 - script: |
    cd $(frontend)
    npm install
    npm run build
    dir
   displayName: 'Build Unicircle React Frontend'

 - script: |
    set JAVA_HOME=D:\Coding\jdk 21
    set PATH=%JAVA_HOME%\bin;%PATH%
    java -version
   displayName: "Set JAVA_HOME for Backend"

 - script: |
    xcopy /s /y "$(Build.SourcesDirectory)\$(frontend)\dist\*" "$(Build.SourcesDirectory)\$(backend)\src\main\resources\static\"
   displayName: 'Copy React build to Spring Boot static directory'

 - script: |
    cd $(backend)
    gradlew.bat clean bootJar -x test
   displayName: 'Build Spring Boot for UniCircle Backend'

 - task: PublishBuildArtifacts@1
   inputs:
    PathtoPublish: '$(backend)\build\libs'
    ArtifactName: 'drop'
   displayName: 'Publish build artifact'

 - task: AzureWebApp@1
   inputs:
    azureSubscription: 'UniCircle-Azure-Connection'
    appName: 'UniCircle'
    package: '$(Pipeline.Workspace)\drop\*.jar'
    appType: 'webApp'
   displayName: 'Deploy to Azure Web App'




