trigger:
  branches:
    include:
      - F104

pool:
  name: UniCircle

jobs:
  - job: Test
    displayName: Run ClubTest
    steps:
      - script: ./gradlew test --tests com.unicircle.ClubTest
        displayName: Run ClubTest
